name: cf-linter and security scan

on:
  pull_request:
  workflow_dispatch:

jobs:
  cloudformation-checks:
    uses: clouddrove/github-shared-workflows/.github/workflows/cf-lint.yml@master
    with:
      cf_file_path: ./aws-control-tower-securityhub-enabler.template
